# 丁妙煊的奇妙工坊 - 构建并部署到 Cloud Run
# 用法：在 dingmiaoxuan 目录下执行
#   gcloud builds submit --config=cloudbuild.yaml --project=YOUR_PROJECT_ID .

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: build
    args:
      - "build"
      - "-t"
      - "${_IMAGE}"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: push
    args:
      - "push"
      - "${_IMAGE}"
    waitFor: ["build"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: deploy
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image=${_IMAGE}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
    waitFor: ["push"]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: "${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${_SERVICE_NAME}:latest"
  _REGION: "asia-southeast1"
  _SERVICE_NAME: "dingmiaoxuan"
